#! /bin/bash
apt install python3
apt install nmap
sudo echo "# cosmo terminal apllication aliases" >> ~/.bashrc
sudo echo "alias cosmo_terminal='cd && cd cosmo-terminal/terminal_cosmo_dir/ && ./terminal_cosmo && cd'" >> ~/.bashrc
apt full-upgrade
apt update
apt full-upgrade
apt update
bash
