#! /usr/bin/python3

import time
from os import *


def clear():
	system("clear")
def  loading_round_1():
	clear()
	print("loading .")
	time.sleep(1)
	clear()
	print("loading ..")
	time.sleep(1)
	clear()
	print("loading ...")
	time.sleep(1)
	clear()


loading_round_1()
loading_round_1()
loading_round_1()

loop = True
while loop == True:
	command = input("cosmo terminal>: ")
	
	if command == "exit":
		exit()
	if command == "help":
		print("current commands:")
		print("		help, exit, clear, execute hack computer.")
	if command == "clear":
		system("clear")
	if command == "execute hack computer":
		ipAnd24 = input('enter the private ip of the router and "/24" at the end>: ')
		system("nmap -sn "+ ipAnd24)
		targetIp = input("enter the target ip >:")
		system("sudo nmap -sS -sU -O -A -vv "+ targetIp)
		system("msfconsole")
#	if command`== "":
